### PR TITLE
fix: issue 116 - custom_streamable_http_endpoint

### LINKED ISSUE #116: `HyperServerOptions::custom_streamable_http_endpoint` is not properly used
**Describe the bug**
I noticed while trying to configure a Streamable HTTP MCP server using `HyperServerOptions` that `custom_streamable_http_endpoint` doesn't seem to work. While digging through the code I noticed `HyperServerOptions impl`'s `pub fn streamable_http_endpoint` instead [returns self.custom_messages_endpoint](https://github.com/rust-mcp-stack/rust-mcp-sdk/blob/2688e1e54bd0a8e3c21e0ea84b0e8d43d60f8917/crates/rust-mcp-sdk/src/hyper_servers/server.rs#L203)

I'll open a PR with a fix shortly. 

What are you using rust-mcp-sdk for?
Select all that apply:

- [x] Developing a MCP Server
- [ ] Developing a MCP Client

**Technical details:**
 - rust-mcp-sdk Version : 0.7.3
 - Cargo features enabled for `rust-mcp-sdk ` : `["server", "macros", "streamable-http", "sse", "hyper-server"]`
 - Environment/OS  (Mac, Linux, Windows, etc) : Mac, Linux

**To Reproduce**
1. Starting with the [streamable http hello world example](https://github.com/rust-mcp-stack/rust-mcp-sdk/tree/main/examples/hello-world-server-streamable-http), add a `custom_streamable_http_endpoint` value to the [HyperServerOptions in main.rs](https://github.com/rust-mcp-stack/rust-mcp-sdk/blob/2688e1e54bd0a8e3c21e0ea84b0e8d43d60f8917/examples/hello-world-server-streamable-http/src/main.rs#L56)
2. Start the server, observe in the server logs that the server still says it's listening for Streamable HTTP connections on `<base_url>/mcp`
3. Confirm with a Streamable HTTP client of your choosing that connections to your custom endpoint are rejected

**Expected behavior**
The server properly listens for streamable HTTP connections on the provided endpoint

### PR DESCRIPTION
**Pull request by jsudano**
### 📌 Summary
I noticed while trying to configure a Streamable HTTP MCP server using `HyperServerOptions` that `custom_streamable_http_endpoint` doesn't seem to work. While digging through the code I noticed `HyperServerOptions impl`'s `pub fn streamable_http_endpoint` instead [returns self.custom_messages_endpoint](https://github.com/rust-mcp-stack/rust-mcp-sdk/blob/2688e1e54bd0a8e3c21e0ea84b0e8d43d60f8917/crates/rust-mcp-sdk/src/hyper_servers/server.rs#L203)

### 🔍 Related Issues

- Fixes #116

### ✨ Changes Made

- Changes `HyperServerOptions::streamable_http_endpoint()` to consume the proper `custom_streamable_http_endpoint` config value.

### 🛠️ Testing Steps
I didn't add unit tests for this because I couldn't find any related tests. Happy to add some unit tests here, not sure if there's a preference on exactly where they should live.

### CODE REVIEW

File: crates/rust-mcp-sdk/src/hyper_servers/server.rs [hunk 1]
```diff
@@ -490,3 +490,170 @@ async fn shutdown_signal(handle: Handle, state: Arc<McpAppState>) {
...
+        // with ssl enabled and valid cert/key paths, validate should succeed
+        let cert_file =
+            NamedTempFile::with_suffix(".pem").expect("Expected to create test cert file");
+        let ssl_cert_path = cert_file
+            .path()
+            .to_str()
+            .expect("Expected to get cert path")
+            .to_string();
+        let key_file =
+            NamedTempFile::with_suffix(".pem").expect("Expected to create test key file");
```
Comment (jsudano) [inline crates/rust-mcp-sdk/src/hyper_servers/server.rs]: Just as a note, these files should be dropped when they go out of scope

Comment (jsudano) [reply crates/rust-mcp-sdk/src/hyper_servers/server.rs]: Many thanks! Happy I could contribute :)
